### ISSUE TITLE
GCP Instance Performance Issues

### ISSUE THREAD

**Issue by sbrupert** [sbrupert/cloud-resume#29]
Seems like everytime we push a deploy with ansible, the GCP instance almost fully locks up. The playbook will get so far along before the system stops reporting into Datadog. 

I'm not sure if this is because of the disk latency or if it's just resource contention on the shared vCPU. But this is preventing me from pushing new builds to the server. 

<img width="1253" alt="Image" src="https://github.com/user-attachments/assets/e1ec1fd1-4218-41ad-9e18-4a5b26e740a3" />

**Comment by sbrupert** [comment]
I'm going to see if stopping the datadog-agent before running the pipeline makes any improvement.

**Comment by sbrupert** [comment]
I think I might have found the root cause for the performance issues. After messing around with disabling services one-by-one, I found that stopping the Datadog agent caused the host to recover quite quickly.  

While I was using `top`, a console message breifly appeared saying something along the lines that the datadog trace payload wasn't abled to be delivered. In the message, it mentioned `top` as the payload.

```yaml
# Datadog APM Config for Auto APM with Docker
datadog_apm_instrumentation_enabled: all
datadog_apm_instrumentation_libraries: ["python"]
datadog_apm_instrumentation_docker_config:
  log_level: info
  output_paths:
    - stderr
  config_sources: BASIC
```

I had setup Datadog's automatic APM so I could see how many services it could trace without additional setup. I guess the answer is _too much for this little GCP instance to handle_. It appears that it was tracing a ton of normal processes running on the system.

This would explain why the server would lock up when running ansible. It was trying to trace all the python code ansible executes on the host. 

I've uninstalled the auto APM stuff, and so far performance is better. I'm going to keep experimenting to figure out how to get things to where they need to be.
